dictionary/urls.py
from django.urls import path
from .views import *


app_name = 'api'

urlpatterns = [
    path('categories/', category_list, name='category_list'),
    path('category/create/', category_create, name='category_create'),
    path('category/detail/<int:pk>/', category_detail, name='category_detail'),
    path('category/update/<int:pk>/', category_update, name='category_update'),
    path('category/update/<int:pk>/', category_update, name='category_update'),
    path('category/delete/<int:pk>/', category_delete, name='category_delete'),
    path('words/', word_list, name='word_list'),
    path('word/create/', word_create, name='word_create'),
    path('word/detail/<int:pk>/', word_detail, name='word_detail'),
    path('word/status_update/<int:pk>/', word_status_update, name='word_status_update'),
    path('word/update/<int:pk>/', word_update, name='word_update'),
    path('word/delete/<int:pk>/', word_delete, name='word_delete'),
]

frontend/urls.py
from django.urls import path
from .views import *


app_name = 'frontend'
urlpatterns = [
    path('', single_view, name='single_word'),
    path('words/', words_view, name='words'),
    path('create/', create_view, name='create')
]

words/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend import views

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('dictionary.urls'))
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.crypto import get_random_string


# Custom User Manager
class AccountManager(BaseUserManager):
    def create_user(self, user_name, password=None):
        if not user_name:
            raise ValueError('Users must have username!')

        user = self.model(
            user_name=user_name
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, user_name, password=None):
        user = self.create_user(user_name, password)

        user.is_admin = True

        user.save(using=self._db)

        return user


# Custom User Model
class Account(AbstractBaseUser):
    user_name = models.CharField(max_length=100, unique=True, verbose_name='Username')
    email = models.EmailField(max_length=255, verbose_name='Email Address')
    profile_photo = models.ImageField(upload_to='profile', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='cover', blank=True, null=True)

    qr_code = models.CharField(max_length=12, unique=True, default=get_random_string, verbose_name='QR Code')

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_name'
    EMAIL_FIELD = 'email'

    objects = AccountManager()

    def __str__(self):
        return self.user_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

dictionary/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name


class Word(models.Model):
    WordType = (
        ('N', 'Noun'),
        ('Adj', 'Adjective'),
        ('V', 'Verb'),
        ('Adv', 'Adverb'),
        ('P', 'Pronoun'),
        ('Num', 'Numeral'),
    )
    StatusType = (
        ('E', 'Excellent'),
        ('G', 'Good'),
        ('P', 'Poor')
    )

    word = models.CharField(max_length=100)
    definition = models.TextField()
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)
    type = models.CharField(blank=True, null=True, max_length=3, choices=WordType)
    status = models.CharField(max_length=1, blank=True, null=True, choices=StatusType, default='P')

    def __str__(self):
        return self.word

frontend/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render

# Create your views here.

dictionary/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from dictionary.models import Category, Word
from dictionary.serializers import CategorySerializer, WordSerializer, WordSerializerRead
import json


@api_view(['GET'])
def category_list(request):
    categories = Category.objects.all()
    serializer = CategorySerializer(categories, many=True)
    return Response(serializer.data)


@api_view(['POST'])
def category_create(request):
    serializer = CategorySerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def category_detail(request, pk):
    try:
        category = Category.objects.get(pk=pk)
    except Category.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = CategorySerializer(category)
    return Response(serializer.data)


@api_view(['PUT'])
def category_update(request, pk):
    try:
        category = Category.objects.get(pk=pk)
    except Category.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = CategorySerializer(category, data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE'])
def category_delete(request, pk):
    try:
        category = Category.objects.get(pk=pk)
    except Category.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    category.delete()
    return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'POST'])
def word_list(request):
    category = request.data
    if category == 'all':
        words = Word.objects.all().order_by('?')
    else:
        words = Word.objects.filter(status=category).order_by('?')
    serializer = WordSerializerRead(words, many=True)
    return Response(serializer.data)


@api_view(['POST'])
def word_create(request):
    serializer = WordSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def word_detail(request, pk):
    try:
        word = Word.objects.get(pk=pk)
    except Word.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = WordSerializerRead(word)
    return Response(serializer.data)


@api_view(['PUT'])
def word_update(request, pk):
    try:
        word = Word.objects.get(pk=pk)
    except Word.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = WordSerializer(word, data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT'])
def word_status_update(request, pk):
    try:
        word = Word.objects.get(pk=pk)
    except Word.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = WordSerializer(word, data={'status': request.data['status']}, partial=True)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE'])
def word_delete(request, pk):
    try:
        word = Word.objects.get(pk=pk)
    except Word.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    word.delete()
    return Response(status=status.HTTP_204_NO_CONTENT)

frontend/views.py
from django.shortcuts import render
from dictionary.models import Category


# Create your views here.
def single_view(request):
    return render(request, 'frontend/single.html')


def words_view(request):
    return render(request, 'frontend/words.html')


def create_view(request):
    categories = Category.objects.all()
    return render(request, 'frontend/create.html', {'categories': categories})

frontend/templates/frontend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Kubik</title>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/icons/rubik.png' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block css %} {% endblock %}
    <!--===============================================================================================-->
</head>
<body>

<div class="container-contact100">

    <div class="wrap-contact100-word">
				<span class="contact100-form-title">
					{% block title %}{% endblock %}
				</span>
        <div class="navigation">
            <a href="{% url 'frontend:single_word' %}" class="btn"><i class="fa fa-file-text-o"></i></a>
            <a href="{% url 'frontend:create' %}" class="btn"><i class="fa fa-plus"></i></a>
            <a href="{% url 'frontend:words' %}" class="btn"><i class="fa fa-list"></i></a>
        </div>
        {% block body %} {% endblock %}
    </div>
</div>

<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
{% block script %} {% endblock %}

</body>
</html>

frontend/templates/frontend/create.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}Add New Word{% endblock %}
{% block body %}
    <form id="word-form">
        <div class="wrap-input100 validate-input">
            <input class="input100" type="text" id="word-input" name="word" placeholder="Word">
            <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input">
            <textarea class="input100" id="definition-textarea" name="message" placeholder="Definition"></textarea>
            <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100">
            <select class="input100 custom-select custom-select-lg" style="border: none;" type="text" id="type-input" name="word">
                <option disabled selected value> -- select a word type -- </option>
                <option value="N">Noun</option>
                <option value="Adj">Adjective</option>
                <option value="V">Verb</option>
                <option value="Adv">Adverb</option>
                <option value="P">Pronoun</option>
                <option value="Num">Number</option>
                <option value="Pre">Preposition</option>
                <option value="Det">Determiner</option>
                <option value="Con">Conjunction</option>
                <option value="Int">Interjection</option>
            </select>
        </div>

        <div class="wrap-input100">
            <select class="input100 custom-select custom-select-lg" style="border: none;" type="text" id="category-input" name="word">
                <option disabled selected value> -- select a category --  </option>
                {% for category in categories %}
                    <option value="{{ category.pk }}">{{ category.category_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="container-contact100-form-btn">
            <button class="contact100-form-btn" id="create-task">
						<span id="button">
							<i class="fa fa-paper-plane-o" aria-hidden="true"></i>
							Add New Word
						</span>
            </button>
        </div>
    </form>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/create.js' %}"></script>
{% endblock %}

frontend/templates/frontend/single.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/single.css' %}">
{% endblock %}
{% block title %}Word{% endblock %}
{% block body %}
    <div id="container">
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/single.js' %}"></script>
{% endblock %}

frontend/templates/frontend/words.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}Words{% endblock %}
{% block body %}
    <div class="status-buttons" style="margin-left: auto; margin-right: auto; width: 300px; display: flex; justify-content: space-between">
        <button class="btn btn-primary" onclick="getWordsList('all').then(data=>populateWords(data))">All</button>
        <button class="btn btn-danger" onclick="getWordsList('P').then(data=>populateWords(data))">Poor</button>
        <button class="btn btn-warning" onclick="getWordsList('G').then(data=>populateWords(data))">Good</button>
        <button class="btn btn-success" onclick="getWordsList('E').then(data=>populateWords(data))">Excellent</button>
    </div>

    <table class="table table-hover table-bordered" style="margin-top: 35px;">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Word</th>
            <th scope="col">Definition</th>
        </tr>
        </thead>
        <tbody id="table-body">
        </tbody>
    </table>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/words.js' %}"></script>
{% endblock %}